### ISSUE TITLE
Overflow X

### ISSUE THREAD

**Issue by bajki** [livelybone/vue-scrollbar-live#1]
Can it be used as horizontal slider?

Thanks

**Comment by livelybone** [comment]
I plan to support it in the next release

**Comment by livelybone** [comment]
> Can it be used as horizontal slider?
> 
> Thanks

I plan to support it in the next version

**Comment by livelybone** [comment]
> Can it be used as horizontal slider?
> 
> Thanks

I plan to support it in the next release

**Comment by livelybone** [comment]
Horizontal slider have been supported since version 5.0.0
