### ISSUE TITLE
Scroll to bottom 

### ISSUE THREAD

**Issue by bajki** [livelybone/vue-scrollbar-live#2]
Is it possible to push scroll to bottom from method

**Comment by livelybone** [comment]
You can use `setDelta` method, see in [Scrollbar.vue](https://github.com/livelybone/vue-scrollbar-live/blob/master/src/Scrollbar.vue#L156)

**Comment by livelybone** [comment]
You can use `scrollTo` prop, see details in [README.md]https://github.com/livelybone/vue-scrollbar-live/blob/master/README.md()
