### ISSUE TITLE
On initialization horizontal scroll not working

### ISSUE THREAD

**Issue by odeal4ik** [livelybone/vue-scrollbar-live#5]
Found that often during initialization, scrollbar scrollbar-x does not have the css property left. And using the mouse is not possible to move the scrollbar. After using shift + wheel on the scrollbar, this property appears and everything works fine.

<div draggable="false" class="scrollbar scrollbar-x" style="width: 858.324px !important; user-select: none;"></div> That is how looks scrollbar-x tag on initialization. Console hasn't any errors.

**Comment by livelybone** [comment]
I can't image how did this happen, everything works find in my demo(https://livelybone.github.io/vue/vue-scrollbar-live/). Can you show your code here?

**Comment by odeal4ik** [comment]
Hello!

`<template>
    <scrollbar
        :maxHeight="maxHeight"
        :marginToWrap="marginToWrap"
        :isMobile="isMobile"
        class="custom-scrollbar"
    >
        <slot />
    </scrollbar>
</template>
`
`import VueScrollbar from 'vue-scrollbar-live';
import 'vue-scrollbar-live/lib/css/index.css';

import './VScroll.css';

export default {
    name: 'custom-scrollbar',
    components: {
        VueScrollbar,
    },
    props: {
        maxHeight: {
            type: String,
            default: '100%',
        },
        marginToWrap: {
            type: Number,
            default: 0,
        },
        isMobile: {
            type: Boolean,
            default: false,
        },
    },
};`

using --->

`<custom-scrollbar class="custom-scrollbar">
            <div class="search-filter__brands-list">
                <template v-for="brand in brandsData">
                    <div class="search-filter__brands-list-item" :key="brand.id" v-if="brand.logo">
                        <a :href="brand.link">
                            <img
                                class="search-filter__brands-image"
                                :src="brand.logo"
                                :alt="brand.name"
                            />
                        </a>
                    </div>
                </template>
            </div>
</custom-scrollbar>
`

in browser --->

![image](https://user-images.githubusercontent.com/8823008/81903870-17e4ed00-95cb-11ea-9e89-03fc4fba46cf.png)

How you can see there is no left property on init on horizontal scroll.
And on hover it not showing scroll bar.

But after scrolling with shift+wheel on win, all is going like in your demo - perfect.

Maybe, i would add this on mounting, on it needs some event on this. Please help.

**Comment by odeal4ik** [comment]
I had noticed one more symptom. By loading page with component it works fine. But if i go to page from other page/route, i see the same problem.

**Comment by odeal4ik** [comment]
All parent elements and wraps have width and heigth.

![image](https://user-images.githubusercontent.com/8823008/81918270-f0981b00-95de-11ea-9436-e04a8acf0a4f.png)

Sory for spam, i try to find a bug.

**Comment by livelybone** [comment]
What is the version you use?

**Comment by livelybone** [comment]
What is the version you use?

**Comment by livelybone** [comment]
> All parent elements and wraps have width and heigth.
> 
> ![image](https://user-images.githubusercontent.com/8823008/81918270-f0981b00-95de-11ea-9436-e04a8acf0a4f.png)
> 
> Sory for spam, i try to find a bug.

Has this bug relationship to the original bug?

**Comment by livelybone** [comment]
> Hello!
> 
> `<template> <scrollbar :maxHeight="maxHeight" :marginToWrap="marginToWrap" :isMobile="isMobile" class="custom-scrollbar" > <slot /> </scrollbar> </template> `
> `import VueScrollbar from 'vue-scrollbar-live';
> import 'vue-scrollbar-live/lib/css/index.css';
> 
> import './VScroll.css';
> 
> export default {
> name: 'custom-scrollbar',
> components: {
> VueScrollbar,
> },
> props: {
> maxHeight: {
> type: String,
> default: '100%',
> },
> marginToWrap: {
> type: Number,
> default: 0,
> },
> isMobile: {
> type: Boolean,
> default: false,
> },
> },
> };`
> 
> using --->
> 
> `<custom-scrollbar class="custom-scrollbar"> <div class="search-filter__brands-list"> <template v-for="brand in brandsData"> <div class="search-filter__brands-list-item" :key="brand.id" v-if="brand.logo"> <a :href="brand.link"> <img class="search-filter__brands-image" :src="brand.logo" :alt="brand.name" /> </a> </div> </template> </div> </custom-scrollbar> `
> 
> in browser --->
> 
> ![image](https://user-images.githubusercontent.com/8823008/81903870-17e4ed00-95cb-11ea-9e89-03fc4fba46cf.png)
> 
> How you can see there is no left property on init on horizontal scroll.
> And on hover it not showing scroll bar.
> 
> But after scrolling with shift+wheel on win, all is going like in your demo - perfect.
> 
> Maybe, i would add this on mounting, on it needs some event on this. Please help.

I cannot run your code successfully. There are some bug in the cod, and missing some of the necessary styles and data

**Comment by livelybone** [comment]
The scrollbar component calculates the height and width in the updated lifecycle. If the children nodes is a single custom component, it is not able to trigger the scrollbar updated lifecycle. Your problem should be caused by this. 
Like what you say, the scrollbar will show after scroll.
If you want it appears in right time, you can call the getHeight or updateHeight method of the scrollbar component instance after you fetched and rendered the data

**Comment by odeal4ik** [comment]
Thank you, i'll try it.

**Comment by livelybone** [comment]
I add MutationObserver to listen DOM change in v5.5.0 to solve this problem. This works well in modern browser and fallbacks to use `hook:updated` in lower version browser.
